"""
Risk state representation for the digital twin.

This module stores risk estimates generated by abnormality,
pathology, aging and multimodal models.
"""

from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Dict, Optional
from datetime import datetime


@dataclass
class RiskState:
    """
    Represents current biological/pathological risk.
    """

    overall_risk: Optional[float] = None

    abnormality_risk: Optional[float] = None
    pathology_risk: Optional[float] = None
    aging_related_risk: Optional[float] = None
    progression_risk: Optional[float] = None

    low_probability: Optional[float] = None
    moderate_probability: Optional[float] = None
    high_probability: Optional[float] = None

    risk_label: str = "unknown"

    confidence: float = 0.0

    timestamp: str = field(
        default_factory=lambda: datetime.utcnow().isoformat()
    )

    metadata: Dict[str, Any] = field(default_factory=dict)

    def update(
        self,
        overall_risk: Optional[float] = None,
        confidence: Optional[float] = None,
        **kwargs: Any,
    ) -> None:
        """
        Update risk state.
        """

        if overall_risk is not None:
            self.overall_risk = float(overall_risk)

        if confidence is not None:
            self.confidence = float(confidence)

        for key, value in kwargs.items():

            if hasattr(self, key):
                setattr(self, key, value)

        self._update_label()

        self.timestamp = datetime.utcnow().isoformat()

    def _update_label(self) -> None:
        """
        Convert numerical risk into a simple qualitative label.
        """

        if self.overall_risk is None:
            self.risk_label = "unknown"
            return

        if self.overall_risk < 0.33:
            self.risk_label = "low"

        elif self.overall_risk < 0.66:
            self.risk_label = "moderate"

        else:
            self.risk_label = "high"

    def to_dict(self) -> Dict[str, Any]:
        """
        Convert to dictionary.
        """
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "RiskState":
        """
        Create RiskState from dictionary.
        """
        return cls(**data)

    def summary(self) -> Dict[str, Any]:
        """
        Return compact risk summary.
        """

        return {
            "overall_risk": self.overall_risk,
            "risk_label": self.risk_label,
            "abnormality_risk": self.abnormality_risk,
            "pathology_risk": self.pathology_risk,
            "aging_related_risk": self.aging_related_risk,
            "progression_risk": self.progression_risk,
            "confidence": self.confidence,
            "timestamp": self.timestamp,
        }