import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/controls/OrbitControls.js';
const subjectId='own_cohort', timepoint='T0', viewport=document.getElementById('twin-viewport'), canvas=document.getElementById('twin-canvas'), loading=document.getElementById('viewer-loading'), dialog=document.getElementById('observation-dialog');
let analysis=null, selectedRegion='palm'; const regionMeshes=new Map();
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x0d1117); const camera=new THREE.PerspectiveCamera(32,1,.1,100); camera.position.set(0,1.5,8.5);
const controls=new OrbitControls(camera,renderer.domElement); controls.enableDamping=true; controls.enablePan=true; controls.minDistance=4; controls.maxDistance=15; controls.target.set(0,.4,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x172033,2.2)); const key=new THREE.DirectionalLight(0xffffff,2.8); key.position.set(4,6,7); scene.add(key); const fill=new THREE.DirectionalLight(0x8bb8ff,1); fill.position.set(-5,2,-4); scene.add(fill); const root=new THREE.Group(); root.rotation.x=-.18; scene.add(root);
const normal=new THREE.MeshStandardMaterial({color:0xc68b72,roughness:.72}), selected=new THREE.MeshStandardMaterial({color:0x66b3ff,roughness:.58,emissive:0x0b2745,emissiveIntensity:.35}), review=new THREE.MeshStandardMaterial({color:0xd6a64f,roughness:.68}), unavailable=new THREE.MeshStandardMaterial({color:0x586174,roughness:.9});
function capsule(name,p,r,l,rot=[0,0,0]){const m=new THREE.Mesh(new THREE.CapsuleGeometry(r,l,8,16),normal.clone());m.name=name;m.position.set(...p);m.rotation.set(...rot);root.add(m);regionMeshes.set(name,m);return m}
capsule('wrist',[0,-2.15,0],.72,1.25); capsule('palm',[0,-.35,0],1.55,2.25); capsule('thumb',[-1.45,0,.02],.48,1.45,[0,0,-.82]); capsule('index',[-1.05,1.95,0],.43,2.15); capsule('middle',[-.35,2.25,0],.46,2.55); capsule('ring',[.42,2.12,0],.45,2.32); capsule('little',[1.12,1.86,0],.40,1.95,[0,0,.08]);
function handAssets(){return (analysis?.assets||[]).filter(x=>x.modality==='hand'&&x.status==='available')}
function regionEvidence(region){const assets=handAssets(); if(region==='palm') return assets.filter(x=>['front','back','side_left','side_right'].includes(x.view)); if(region==='thumb') return assets.filter(x=>x.view==='thumb'); return assets.filter(x=>x.zone_id===region)}
function status(region){const hand=regionEvidence(region); const all=analysis?.assets||[]; return {macro:hand.length>0, macroCount:hand.length, tissue:all.some(x=>x.modality==='wsi'&&x.status==='available'&&x.subject_id===subjectId&&x.timepoint===timepoint&&x.region_id===region), molecular:all.some(x=>x.modality==='rna'&&x.status==='available'&&x.subject_id===subjectId&&x.timepoint===timepoint&&x.region_id===region)}}
function mat(region){const s=status(region);if(!s.macro&&!s.tissue&&!s.molecular)return unavailable.clone();if(!s.macro||s.molecular&&!s.tissue)return review.clone();return normal.clone()}
function setEvidenceStatus(id,label){const el=document.getElementById(id);if(el)el.textContent=label}
function renderMacroEvidence(region){const items=regionEvidence(region);const preview=document.getElementById('macro-preview'),image=document.getElementById('macro-image'),filename=document.getElementById('macro-filename'),view=document.getElementById('macro-view'); if(!items.length){preview.hidden=true;image.removeAttribute('src');return} const item=items[0]; image.src=`/api/hand/evidence/${encodeURIComponent(item.asset_id)}`; image.alt=`Macro evidence · ${item.view||item.filename}`; filename.textContent=item.filename||'hand image'; view.textContent=(item.view||'view').replaceAll('_',' '); preview.hidden=false}
function selectRegion(region,focus=true){if(!regionMeshes.has(region))return;selectedRegion=region;for(const[id,m]of regionMeshes)m.material=id===region?selected.clone():mat(id);document.getElementById('zone-label').textContent=region;document.getElementById('region-title').textContent=region.charAt(0).toUpperCase()+region.slice(1);document.getElementById('form-region').value=region;const s=status(region);
  document.getElementById('macro-state').textContent=s.macro?(s.macroCount>1?'Available':'Available'):'No evidence'; document.getElementById('macro-detail').textContent=s.macro?`${s.macroCount} region-relevant hand image${s.macroCount===1?'':'s'} available. Preview shows the first registered view.`:'No explicitly region-relevant hand image is currently available.'; setEvidenceStatus('macro-status',s.macro?'OBSERVED':'NONE'); renderMacroEvidence(region);
  document.getElementById('tissue-state').textContent=s.tissue?'Available / linked':'Unavailable'; document.getElementById('tissue-detail').textContent=s.tissue?'Tissue-level evidence is explicitly linked to this region.':'No tissue / WSI evidence is explicitly linked to this region.'; setEvidenceStatus('tissue-status',s.tissue?'LINKED':'NONE');
  document.getElementById('cellular-state').textContent='Unavailable'; document.getElementById('cellular-detail').textContent='Cellular conclusions require microscopy / cellular data explicitly linked to this region.'; setEvidenceStatus('cellular-status','NONE');
  document.getElementById('molecular-state').textContent=s.molecular?'Available / linked':'Unavailable'; document.getElementById('molecular-detail').textContent=s.molecular?'Molecular measurements are explicitly linked to this region.':'No molecular measurements are explicitly linked to this region.'; setEvidenceStatus('molecular-status',s.molecular?'LINKED':'NONE');
  document.getElementById('confidence-state').textContent=s.macro?'Observed input':'No evidence'; document.getElementById('evidence-level').textContent=s.macro?'Macro / observed data':'Availability only';
  if(focus){controls.target.set(0,region==='wrist'?-1.2:region==='palm'?-0.35:1.3,0);controls.update()}}
async function refresh(){try{const r=await fetch(`/api/hand/analysis?subject_id=${encodeURIComponent(subjectId)}&timepoint=${encodeURIComponent(timepoint)}`);if(!r.ok)throw Error();analysis=await r.json();const c=analysis.coverage||{};document.getElementById('coverage-macro').textContent=`Macro ${c.macro??0}%`;document.getElementById('coverage-micro').textContent=`Tissue ${c.micro??0}%`;document.getElementById('coverage-cellular').textContent='Cellular —';document.getElementById('coverage-molecular').textContent=`Molecular ${c.molecular??0}%`;document.getElementById('twin-status').textContent=`${handAssets().length} macro observation${handAssets().length===1?'':'s'} loaded`;selectRegion(selectedRegion,false)}catch(_){document.getElementById('twin-status').textContent='Evidence unavailable'}finally{loading.remove()}}
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects([...regionMeshes.values()],false);if(hits.length)selectRegion(hits[0].object.name)});
function reset(){camera.position.set(0,1.5,8.5);controls.target.set(0,.4,0);root.rotation.y=0;controls.update();document.getElementById('zoom-label').textContent='100%'} document.getElementById('reset-view').onclick=reset;document.getElementById('rotate-left').onclick=()=>root.rotation.y-=Math.PI/9;document.getElementById('rotate-right').onclick=()=>root.rotation.y+=Math.PI/9;document.getElementById('zoom-in').onclick=()=>{camera.position.multiplyScalar(.86);controls.update()};document.getElementById('zoom-out').onclick=()=>{camera.position.multiplyScalar(1.16);controls.update()};document.getElementById('zoom-region').onclick=()=>{camera.position.multiplyScalar(.84);controls.update()};document.getElementById('deep-analysis').onclick=()=>{const s=status(selectedRegion);alert(s.tissue?`Deep analysis for ${selectedRegion}: linked tissue evidence exists, but cellular interpretation is not enabled without explicit microscopy linkage.`:`Deep analysis for ${selectedRegion}: no linked tissue/cellular evidence is currently available. The system will not invent it.`)};document.getElementById('add-observation').onclick=()=>dialog.showModal();document.querySelector('.close').onclick=()=>dialog.close();
document.getElementById('register-observation').onclick=async e=>{e.preventDefault();const file=document.getElementById('observation-file').files[0];if(!file)return;const modality=document.getElementById('form-modality').value,endpoint={Photo:'hand',Video:'video',Microscopy:'wsi',Measurements:'metadata','Molecular data':'rna'}[modality],body=new FormData();body.append('file',file);body.append('subject_id',subjectId);body.append('timepoint',timepoint);body.append('view',selectedRegion);const b=e.currentTarget;b.disabled=true;b.textContent='Registering…';try{const r=await fetch(`/api/upload/${endpoint}`,{method:'POST',body}),j=await r.json();if(!r.ok)throw Error(j.detail||'Upload failed');dialog.close();await refresh();alert(`Observation registered for ${selectedRegion}. Biological inference is not established automatically.`)}catch(err){alert(err.message)}finally{b.disabled=false;b.textContent='Register observation'}};
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}resize();animate();selectRegion('palm',false);refresh();
