(() => {
  const SUBJECT = 'own_cohort';
  const LEVELS = [['macro','Macro'],['tissue','Tissue'],['cellular','Cellular'],['molecular','Molecular']];
  const TIMEPOINTS = ['all','T0','T1','T2','T3'];
  let target = {spatial_id:'hand',path:['Hand'],location_name:'Hand'};
  let timepointFilter='all'; let levelFilter='all'; let search=''; let includeArchived=false;

  const inspector=document.querySelector('.inspector');
  if(!inspector)return;
  const root=document.createElement('section');
  root.className='roi-observation-manager';
  root.innerHTML=`<div class="roi-om-head"><div><span class="section-kicker">OBSERWACJE REGIONU</span><h3>Obserwacje <span class="roi-om-context">· Hand</span></h3></div><button class="roi-om-add" type="button">＋ Dodaj obserwację</button></div><div class="roi-om-tools"><input id="roi-om-search" placeholder="Szukaj obserwacji…"><select id="roi-om-level"><option value="all">Wszystkie poziomy</option>${LEVELS.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select><select id="roi-om-time">${TIMEPOINTS.map(v=>`<option value="${v}">${v==='all'?'Wszystkie':v}</option>`).join('')}</select><label><input id="roi-om-archived" type="checkbox"> Archiwum</label></div><div class="roi-om-list"></div>`;
  const actions=inspector.querySelector('.inspector-actions'); (actions||inspector).before(root);

  const style=document.createElement('style'); style.textContent=`
    .roi-observation-manager{margin-top:12px;padding-top:11px;border-top:1px solid #e1e6ea}.roi-om-head{display:flex;justify-content:space-between;align-items:baseline;gap:8px}.roi-om-head h3{margin:2px 0 0;font-size:12px;color:#26343e}.roi-om-context{font-size:7px;color:#8a969f;font-weight:500}.roi-om-add{border:1px solid #146b55;background:#146b55;color:#fff;border-radius:7px;padding:6px 8px;font-size:8px;font-weight:750;cursor:pointer}.roi-om-tools{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin:8px 0}.roi-om-tools input,.roi-om-tools select{box-sizing:border-box;width:100%;padding:6px;border:1px solid #d5dde2;border-radius:7px;background:#fff;font-size:8px}.roi-om-tools input:first-child{grid-column:1/-1}.roi-om-tools label{display:flex;align-items:center;gap:4px;font-size:7px;color:#68757e}.roi-om-list{display:grid;gap:5px;max-height:390px;overflow:auto}.roi-om-card{border:1px solid #e1e6ea;border-radius:8px;background:#fafbfc;padding:7px}.roi-om-card.archived{opacity:.62}.roi-om-card-head{display:flex;justify-content:space-between;gap:5px}.roi-om-title{font-size:8px;font-weight:800;color:#34424c}.roi-om-badge{font-size:6px;color:#146b55;white-space:nowrap}.roi-om-meta{margin-top:3px;font-size:7px;color:#7d8991;line-height:1.4}.roi-om-actions{display:flex;gap:4px;margin-top:5px}.roi-om-actions button{flex:1;border:1px solid #d5dde2;background:#fff;color:#53616c;border-radius:6px;padding:4px;font-size:7px;font-weight:750;cursor:pointer}.roi-om-actions .danger{color:#9a4b3c}.roi-om-empty{padding:8px;border:1px dashed #d5dde2;border-radius:8px;color:#8a969f;font-size:8px}.om-history-item{line-height:1.45}.om-diff{margin:3px 0 0;padding:4px;background:#f3f5f6;border-radius:5px;font-family:monospace;font-size:7px}`; document.head.appendChild(style);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pathText=()=>target.path.join(' > ');

  function ensureDialog(){let d=document.getElementById('om-dialog');if(d)return d;d=document.createElement('dialog');d.id='om-dialog';d.className='om-dialog';d.innerHTML=`<form class="om-form" id="om-form"><h3 id="om-form-title">Dodaj obserwację biologiczną</h3><p class="om-subtitle" id="om-form-subtitle"></p><input id="om-id" type="hidden"><label>Poziom biologiczny</label><select id="om-level">${LEVELS.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select><label>Modality / metoda</label><input id="om-modality" value="manual-entry"><label>Nazwa obserwacji</label><input id="om-name" required><label>Wartość</label><textarea id="om-value"></textarea><label>Źródło</label><input id="om-source" value="manual-entry"><label>Autor</label><input id="om-author" value="local-user"><label>Data obserwacji</label><input id="om-observed-at" type="datetime-local"><label>Notatka</label><textarea id="om-notes"></textarea><div class="om-form-actions"><button type="button" id="om-cancel">Anuluj</button><button type="submit" class="primary">Zapisz obserwację</button></div></form>`;document.body.appendChild(d);document.getElementById('om-cancel').onclick=()=>d.close();document.getElementById('om-form').onsubmit=save;return d}
  function ensureDetail(){let d=document.getElementById('om-detail-dialog');if(d)return d;d=document.createElement('dialog');d.id='om-detail-dialog';d.className='om-dialog';d.innerHTML=`<div class="om-form"><h3>Szczegóły obserwacji</h3><p class="om-subtitle" id="om-detail-subtitle"></p><div id="om-detail-content"></div><div class="om-form-actions"><button type="button" id="om-detail-close">Zamknij</button></div></div>`;document.body.appendChild(d);document.getElementById('om-detail-close').onclick=()=>d.close();return d}
  async function load(){const p=new URLSearchParams({subject_id:SUBJECT,include_archived:String(includeArchived),spatial_id:target.spatial_id});if(timepointFilter!=='all')p.set('timepoint',timepointFilter);if(levelFilter!=='all')p.set('biological_level',levelFilter);const r=await fetch(`/api/observations?${p}`);if(!r.ok)throw Error('Nie udało się pobrać obserwacji.');let items=(await r.json()).observations||[];if(search)items=items.filter(x=>[x.name,x.source,x.modality,x.location_name,x.author].join(' ').toLowerCase().includes(search.toLowerCase()));return items}
  async function render(){root.querySelector('.roi-om-context').textContent=`· ${pathText()}`;const list=root.querySelector('.roi-om-list');list.innerHTML='<div class="roi-om-empty">Ładowanie obserwacji…</div>';try{const items=await load();if(!items.length){list.innerHTML='<div class="roi-om-empty">Brak obserwacji dla wybranych filtrów.</div>';return}list.innerHTML=items.map(x=>`<article class="roi-om-card ${x.status==='archived'?'archived':''}"><div class="roi-om-card-head"><span class="roi-om-title">${esc(x.name)}</span><span class="roi-om-badge">${esc(x.biological_level)} · ${esc(x.timepoint)}</span></div><div class="roi-om-meta"><b>${esc(x.modality)}</b> · ${esc(x.source)} · ${esc(x.observed_at||'')} · v${esc(x.version||1)} · ${esc(x.author||'local-user')}</div><div class="roi-om-actions"><button data-detail="${esc(x.id)}">Szczegóły</button><button data-edit="${esc(x.id)}">Edytuj</button>${x.status==='archived'?`<button data-restore="${esc(x.id)}">Przywróć</button>`:`<button class="danger" data-archive="${esc(x.id)}">Archiwizuj</button>`}</div></article>`).join('');list.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>showDetail(b.dataset.detail));list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));list.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>lifecycle(b.dataset.archive,'archive'));list.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>lifecycle(b.dataset.restore,'restore'))}catch(e){list.innerHTML=`<div class="roi-om-empty">${esc(e.message)}</div>`}}
  function edit(id=null){const d=ensureDialog();document.getElementById('om-id').value=id||'';document.getElementById('om-form-title').textContent=id?'Edytuj obserwację':'Dodaj obserwację';document.getElementById('om-form-subtitle').textContent=pathText();document.getElementById('om-level').value='cellular';document.getElementById('om-modality').value='manual-entry';document.getElementById('om-name').value='';document.getElementById('om-value').value='';document.getElementById('om-source').value='manual-entry';document.getElementById('om-author').value='local-user';document.getElementById('om-observed-at').value=new Date().toISOString().slice(0,16);document.getElementById('om-notes').value='';if(id)fetch(`/api/observations/${encodeURIComponent(id)}`).then(r=>r.json()).then(({observation:x})=>{document.getElementById('om-level').value=x.biological_level||'cellular';document.getElementById('om-modality').value=x.modality||'manual-entry';document.getElementById('om-name').value=x.name||'';document.getElementById('om-value').value=typeof x.value==='string'?x.value:JSON.stringify(x.value??'',null,2);document.getElementById('om-source').value=x.source||'manual-entry';document.getElementById('om-author').value=x.author||'local-user';document.getElementById('om-notes').value=x.notes||'';document.getElementById('om-observed-at').value=String(x.observed_at||'').slice(0,16)});d.showModal()}
  function val(s){s=s.trim();if(!s)return null;try{return JSON.parse(s)}catch{return s}}
  async function save(e){e.preventDefault();const id=document.getElementById('om-id').value,p={biological_level:document.getElementById('om-level').value,modality:document.getElementById('om-modality').value.trim()||'manual-entry',name:document.getElementById('om-name').value.trim(),value:val(document.getElementById('om-value').value),source:document.getElementById('om-source').value.trim()||'manual-entry',author:document.getElementById('om-author').value.trim()||'local-user',observed_at:document.getElementById('om-observed-at').value?new Date(document.getElementById('om-observed-at').value).toISOString():new Date().toISOString(),notes:document.getElementById('om-notes').value.trim()};if(!p.name)return;const create=!id,body=create?{...p,subject_id:SUBJECT,timepoint:timepointFilter==='all'?'T0':timepointFilter,spatial_id:target.spatial_id,location_name:target.location_name,location_level:'site'}:p;const r=await fetch(create?'/api/observations':`/api/observations/${encodeURIComponent(id)}`,{method:create?'POST':'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){alert((await r.json()).detail||'Nie udało się zapisać obserwacji.');return}ensureDialog().close();window.dispatchEvent(new CustomEvent('testhp:observation-changed'));render()}
  async function lifecycle(id,action){const reason=prompt(action==='archive'?'Powód archiwizacji:':'Powód przywrócenia:','')??'';const r=await fetch(`/api/observations/${encodeURIComponent(id)}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({author:'local-user',reason})});if(!r.ok){alert('Operacja nie powiodła się.');return}render()}
  async function showDetail(id){const r=await fetch(`/api/observations/${encodeURIComponent(id)}`);if(!r.ok)return;const {observation:x}=await r.json(),d=ensureDetail(),value=typeof x.value==='string'?x.value:JSON.stringify(x.value??null,null,2),audit=(x.audit||[]).map(a=>`<div class="om-history-item"><b>v${esc(a.version)}</b> · ${esc(a.action)} · ${esc(a.at)} · ${esc(a.author||'local-user')}${a.reason?` · ${esc(a.reason)}`:''}${a.diff?`<div class="om-diff">${esc(JSON.stringify(a.diff))}</div>`:''}</div>`).join('');document.getElementById('om-detail-subtitle').textContent=`${x.location_name} · ${x.timepoint}`;document.getElementById('om-detail-content').innerHTML=`<div class="om-detail"><div class="om-detail-row"><b>Poziom</b><span>${esc(x.biological_level)}</span></div><div class="om-detail-row"><b>Modality</b><span>${esc(x.modality)}</span></div><div class="om-detail-row"><b>Nazwa</b><span>${esc(x.name)}</span></div><div class="om-detail-row"><b>Wartość</b><span><pre>${esc(value)}</pre></span></div><div class="om-detail-row"><b>Źródło</b><span>${esc(x.source)}</span></div><div class="om-detail-row"><b>Evidence</b><span>${esc(x.evidence_id||'brak jawnego powiązania')}</span></div><div class="om-detail-row"><b>Autor</b><span>${esc(x.author||'local-user')}</span></div><div class="om-detail-row"><b>Status</b><span>${esc(x.status||'active')}</span></div><div class="om-detail-row"><b>Wersja</b><span>${esc(x.version||1)}</span></div></div><div class="om-history"><strong>Historia zmian</strong>${audit||'<div class="om-history-item">Brak historii.</div>'}</div>`;d.showModal()}
  root.querySelector('#roi-om-search').oninput=e=>{search=e.target.value;render()};root.querySelector('#roi-om-level').onchange=e=>{levelFilter=e.target.value;render()};root.querySelector('#roi-om-time').onchange=e=>{timepointFilter=e.target.value;render()};root.querySelector('#roi-om-archived').onchange=e=>{includeArchived=e.target.checked;render()};root.querySelector('.roi-om-add').onclick=()=>edit();
  window.addEventListener('testhp:spatial-layer-changed',e=>{const d=e.detail||{};target={spatial_id:d.spatial_id||d.id||'hand',path:d.path||[d.target||'Hand'],location_name:d.target||'Hand'};render()});window.addEventListener('testhp:observation-changed',render);render();
})();
